// This file was generated by Slater.app - HOME.js


// Fade out hero CTA
gsap.to("#FadeOUT", {
  scrollTrigger: {
    trigger: "#MainWrap", // Use the body as the trigger
    start: "top top", // Start the animation when the top of the body is at the top of the viewport
    end: "2% top",
    scrub: true, // Smoothly scrubs the animation in sync with the scroll
    onEnterBack: () => {
      // Set display to block when scrolling back up
      document.querySelector("#FadeOUT").style.display = "flex";
    }
  },
  opacity: 0, // Fade out to 0 opacity
  filter: "blur(10px)", // Apply a blur effect
  ease: "power2.out", // Use an easing function for a smoother transition
  onComplete: () => {
    // Set display to none once the animation completes
    document.querySelector("#FadeOUT").style.display = "none";
  }
});

//home TL animation
//home TL animation
//home TL animation

// Initialize the timeline
const HOME_tl = gsap.timeline();

// Split text for HeroTitle and HeroText
const HeroTitle = new SplitText('#HeroTitle', {
  type: "lines,chars,words",
  linesClass: "lines-js",
  wordsClass: "word-js",
  charsClass: "char-js"
});
const HeroText = new SplitText('#HeroText', {
  type: "lines,chars,words",
  linesClass: "lines-js",
  wordsClass: "word-js",
  charsClass: "char-js"
});

// Get split text elements
const HeroTitleWords = HeroTitle.chars;
const HeroTextWords = HeroText.lines;

// Get other elements
const MotionBtn = document.getElementById("MotionBtn");
const RedDot = document.getElementById("RED_DOT");
const marquee1 = document.getElementById("M1");
const marquee2 = document.getElementById("M2");

// Add animations to the timeline
HOME_tl.from(HeroTitleWords, {
    delay: 0.2,
    duration: 1.6,
    ease: 'expo.out',
    yPercent: 200,
    stagger: 0.04,
  })
  .from(HeroTextWords, {
    duration: 0.8,
    ease: 'expo.out',
    opacity: 0,
    yPercent: 40,
    // stagger: 0.1,
  }, "<50%")
  .from(MotionBtn, {
    duration: 0.8,
    ease: 'expo.out',
    opacity: 0,
    yPercent: 20,
  }, "<44%")
  .from(RedDot, {
    duration: 0.8,
    ease: 'expo.out',
    opacity: 0,
    filter: 'blur(10px)',
    yPercent: 20,
  }, "<12%")
  .from([marquee1, marquee2], {
    duration: 1.5,
    ease: 'power2.out',
    y: '40vh',
  }, "<40%");

// Initialize SplitText
const MagicTitle = new SplitText('#MagicTitle', {
  type: "lines,chars,words",
  linesClass: "lines-js",
  wordsClass: "word-js",
  charsClass: "char-js"
});

// Get split text elements
const MagicTitleWords = MagicTitle.chars;

// Add animations to the timeline with a scroll trigger
gsap.from(MagicTitleWords, {
  scrollTrigger: {
    trigger: '#TRIGY', // Set the trigger element
    start: 'top 20%', // Start 20% sooner
    end: 'bottom top', // Define an end point if needed
    scrub: true, // Sync animation with scroll position
  },
  duration: 1.6,
  ease: 'expo.out',
  yPercent: 200,
  stagger: 0.04,
});


