// This file was generated by Slater.app - WORK.js


//hidden older work
//hidden older work
//hidden older work

const button = document.getElementById("SEE_OLD_WORK");
const container = document.getElementById("WORK_CONTAINER");

// Button fade-in on scroll
gsap.from(button, {
  duration: 2,
  opacity: 0,
  yPercent: 40,
  ease: 'power3.out',
  scrollTrigger: {
    trigger: button,
    start: 'top 133%',
  }
});

// Expand container on click
button.addEventListener("click", function () {
  const fullHeight = container.scrollHeight;

  gsap.to(container, {
    height: fullHeight,
    duration: 1,
    ease: "power2.inOut",
    onComplete: () => {
      container.style.height = "auto";
    }
  });

  gsap.to(button, {
    opacity: 0,
    duration: 0.5,
    ease: "power1.out",
    onComplete: () => button.style.display = "none"
  });
});

//onload
//onload
//onload

const WORKS_tl = gsap.timeline();

const HeroTitle = new SplitText('#HeroTitle', {
  type: "lines,chars,words",
  linesClass: "lines-js",
  wordsClass: "word-js",
  charsClass: "char-js"
});

const HeroTitleWords = HeroTitle.chars;
const WTL = document.querySelector("#work_title");
const WorkTXT = document.querySelector("#Work_txt");
const DARK_section = document.getElementById("DARK_section");
const First_Content = document.getElementById("First_content");

WORKS_tl
  .from(HeroTitleWords, {
    delay: 0.33,
    duration: 0.8,
    ease: 'expo.out',
    yPercent: 100,
    stagger: 0.03,
  }, "pair")
  .from(DARK_section, {
    duration: 1.2,
    y: '50vh',
    ease: 'power2.out',
  }, "pair")
  .from(First_Content, {
    duration: 0.6,
    opacity: 0,
    filter: "blur(5px)",
  }, "-=0.6")
  .from(WTL, {
    duration: 0.8,
    opacity: 0,
    ease: 'expo.out',
    yPercent: 120,
  }, "-=0.3")
  .from(WorkTXT, {
    duration: 0.8,
    opacity: 0,
    ease: 'expo.out',
    yPercent: 100,
  }, "-=0.4");

// ________ batch scrolltrigger ________
// ________ batch scrolltrigger ________
const WORK_GRID = document.querySelector("#WORK_GRID");

if (WORK_GRID) {
  const Items = Array.from(WORK_GRID.children);

  gsap.set(Items, { // Apply opacity/yPercent to the child elements, not the grid itself
    opacity: 0,
    yPercent: 40
  });

  ScrollTrigger.batch(Items, {
    start: 'top 133%',
    onEnter: (elements) => {
      gsap.to(elements, {
        duration: 2,
        opacity: 1,
        yPercent: 0,
        ease: 'power3.out',
        stagger: 0.2
      });
    }
  });
}


