// This file was generated by Slater.app - QUIZ .js


jQuery(function ($) {
  $('#start_btn').on('click', function () {
    $('#OPENING').hide();
    $('#TheQuiz').show();
  });
});

jQuery(function ($) {
  var questions = [
  {
    text: "Who is this?",
    choices: ["Swimming doggo", "Pool doggo", "Super doggo", "Gangster doggo"],
    answer: "Pool doggo",
    img: "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9baacf801b7bf3d2952b5_swim%20doggo.avif"
  },
  {
    text: "Do dolphins make rainbows?",
    choices: ["Yes", "For sure !!", "HELL YEAAAHH!!", "no"],
    answer: "no",
    img: "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9baabf7941818f9206d11_raredolphin.avif"
  },
  {
    text: "Whaaat?¿",
    choices: ["beans", "ǝɯ ʞɔᴉlʞƆ", "24", "get money"],
    answer: "ǝɯ ʞɔᴉlʞƆ",
    img: "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9baac1c9bea03eb04d9a4_jake%20qute.gif"
  },
  {
    text: "You will never beat my quiz",
    choices: ["run", "do nothing", "be scared", "fight"],
    answer: "fight",
    img: "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9baace5f540f75bcc8a81_batman.gif"
  },
  {
    text: "69 * 420",
    choices: ["28980", "38760", "24840", "18980"],
    answer: "28980",
    img: "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9baaccf0f44a242318fcc_math.gif"
  },
  {
    text: "This froggo is...",
    choices: ["cute", "beautiful", "poisonous", "all answers are correct"],
    answer: "all answers are correct",
    img: "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9baab8336152373ee545b_froggo.avif"
  },
  {
    text: "Oops, you touched the froggo!",
    choices: ["Whoobie doobie", "Dance with shroom", "Get it together", "Trip it out :3"],
    answer: "Get it together",
    img: "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9cca79bb46fd660bdc4a9_3333.gif"
  },
  {
    text: "Do you think you're going to win?",
    choices: ["I'm doing fine", "Uhhhh...", "I hope so", ":I"],
    answer: "I'm doing fine",
    img: "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9baacd5cd5274f0549189_fine.gif"
  },
  {
    text: "Boss, how do we make this guy lose?",
    choices: ["lose now", "Click here", "Go final question", "call Rimbo"],
    answer: "Go final question",
    img: "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9baae6f86c2474a3b427a_calling.gif"
  },
  {
    text: "Who is Rimbo?",
    choices: ["Cool dude", "God of vibes", "Funny guy", "My man!"],
    answer: "God of vibes",
    img: "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9cb9663c31098a3e52ed9_MP4%20to%20GIF%20test.gif"
  }];

  var questionIndex = 0;
  var score = 0;

  function populate() {
    if (questionIndex >= questions.length) {
      showScores(); // End quiz if all questions are answered
      return;
    }

    var currentQuestion = questions[questionIndex];

    $("#QUESTION").text(currentQuestion.text);
    $("#BTN_1 .btn-animate-chars__text").text(currentQuestion.choices[0]);
    $("#BTN_2 .btn-animate-chars__text").text(currentQuestion.choices[1]);
    $("#BTN_3 .btn-animate-chars__text").text(currentQuestion.choices[2]);
    $("#BTN_4 .btn-animate-chars__text").text(currentQuestion.choices[3]);
    $("#Quiz_IMG").attr("src", currentQuestion.img);

    showProgress();
  }

  function showProgress() {
    var currentQuestionNumber = questionIndex + 1;
    $("#progress").text("Question " + currentQuestionNumber + " of " + questions.length);
  }

  function handleAnswerClick() {
    var selectedAnswer = $(this).find(".btn-animate-chars__text").text();
    var correctAnswer = questions[questionIndex].answer;

    if (selectedAnswer === correctAnswer) {
      score++;
    }

    questionIndex++; // Move to next question

    if (questionIndex >= questions.length) {
      showScores(); // Call showScores() to properly display the end screen
    } else {
      populate(); // Load next question
    }
  }

  function showScores() {
    var image_ref = score < 5 ?
      "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9baac326fc8390883ba7e_sad.gif" :
      score < 10 ?
      "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9baacd16a1ddbaa367246_clap.gif" :
      "https://cdn.prod.website-files.com/5b9ab5ab7d8a747bcc7b3216/67e9d1951ac3a50582bc8e90_Tim%20And%20Eric%20Reaction%20GIF.gif";

    // Using GSAP to show the end screen with a fade-in effect
    gsap.set(".ending_screen", { display: "flex" });
    gsap.set(".thequiz", { display: "none" });

    $("#END_IMG").attr("src", image_ref);
    $("#SCORE").text("Your score: " + score + " / " + questions.length);
  }

  // Attach click event listeners to the answer buttons
  $("#BTN_1, #BTN_2, #BTN_3, #BTN_4").on("click", handleAnswerClick);

  // Start the quiz by populating the first question
  populate();
});


